if (typeof flashcardData === 'undefined') var flashcardData = {};

Object.assign(flashcardData, {
    "Verbs 1": [
        { korean: "일하다", romanization: "ilhada", meaning: "to work" },
        { korean: "만들다", romanization: "mandeulda", meaning: "to make" },
        { korean: "하다", romanization: "hada", meaning: "to do" },
        { korean: "끄다", romanization: "kkeuda", meaning: "to turn off" },
        { korean: "닫다", romanization: "datda", meaning: "to close (regular ㄷ)" },
        { korean: "열다", romanization: "yeolda", meaning: "to open" },
        { korean: "쓰다", romanization: "sseuda", meaning: "to use" },
        { korean: "입다", romanization: "ipda", meaning: "to wear (regular ㅂ)" },
        { korean: "벗다", romanization: "beotda", meaning: "to wear off (regular ㅅ)" },
        { korean: "씻다", romanization: "ssitda", meaning: "to wash (regular ㅅ)" },
        { korean: "두다", romanization: "duda", meaning: "to put" },
        { korean: "싣다", romanization: "sitda", meaning: "to load (irregular ㄷ)" },
        { korean: "잡다", romanization: "japda", meaning: "to catch/hold (regular ㅂ)" },
        { korean: "쥐다", romanization: "jwida", meaning: "to hold" },
        { korean: "집다", romanization: "jipda", meaning: "to pick (regular ㅂ)" },
        { korean: "줍다", romanization: "jupda", meaning: "to pick/select (regular ㅂ)" },
        { korean: "자르다", romanization: "jareuda", meaning: "to cut (irregular ㅡ)" },
        { korean: "썰다", romanization: "sseolda", meaning: "to chop" },
        { korean: "갈다", romanization: "galda", meaning: "to sharpen (blade)" },
        { korean: "매다", romanization: "maeda", meaning: "to tie" },
        { korean: "밀다", romanization: "milda", meaning: "to push" },
        { korean: "끌다", romanization: "kkeulda", meaning: "to pull/drag" },
        { korean: "나르다", romanization: "nareuda", meaning: "to carry" },
        { korean: "뽑다", romanization: "ppopda", meaning: "to unplug" },
        { korean: "걸다", romanization: "geolda", meaning: "to hang" },
        { korean: "오다", romanization: "oda", meaning: "to come" },
        { korean: "가다", romanization: "gada", meaning: "to go" },
        { korean: "들다", romanization: "deulda", meaning: "to enter" },
        { korean: "서다", romanization: "seoda", meaning: "to stand" },
        { korean: "앉다", romanization: "anda", meaning: "to sit" },
        { korean: "일어나다", romanization: "ireonada", meaning: "to get up" },
        { korean: "먹다", romanization: "meokda", meaning: "to eat" },
        { korean: "마시다", romanization: "masida", meaning: "to drink" },
        { korean: "쉬다", romanization: "swida", meaning: "to rest" },
        { korean: "끝내다", romanization: "kkeutnaeda", meaning: "to end/finish" },
        { korean: "마무리하다", romanization: "mamurihada", meaning: "to pack up/finishing up" },
        { korean: "읽다", romanization: "ikda", meaning: "to read" },
    ],

    "Verbs 2": [
        { korean: "믿다", romanization: "mitda", meaning: "to believe (regular ㄷ)" },
        { korean: "듣다", romanization: "deutda", meaning: "to listen (irregular ㄷ)" },
        { korean: "묻다", romanization: "mutda", meaning: "to ask (irregular ㄷ)" },
        { korean: "지키다", romanization: "jikida", meaning: "to follow/obey" },
        { korean: "빌리다", romanization: "billida", meaning: "to borrow" },
        { korean: "피우다", romanization: "piuda", meaning: "to smoke" },
        { korean: "나누다", romanization: "nanuda", meaning: "to divide" },
        { korean: "팔다", romanization: "palda", meaning: "to sell" },
        { korean: "짓다", romanization: "jitda", meaning: "to build (irregular ㅅ)" },
        { korean: "긋다", romanization: "geutda", meaning: "to draw a line (irregular ㅅ)" },
        { korean: "젓다", romanization: "jeotda", meaning: "to stir (irregular ㅅ)" },
        { korean: "빗다", romanization: "bitda", meaning: "to comb (regular ㅅ)" },
        { korean: "잇다", romanization: "itda", meaning: "to connect (irregular ㅅ)" },
        { korean: "널다", romanization: "neolda", meaning: "to hang up/to dry out (laundry)" },
        { korean: "담그다", romanization: "damgeuda", meaning: "to soak" },
        { korean: "오르다", romanization: "oreuda", meaning: "to ascend" },
        { korean: "올라오다", romanization: "ollaoda", meaning: "to come up" },
        { korean: "돌아오다", romanization: "doraoda", meaning: "to come back" },
        { korean: "기르다", romanization: "gireuda", meaning: "to raise/grow" },
        { korean: "휘다", romanization: "hwida", meaning: "to bend" },
        { korean: "뛰다", romanization: "ttwida", meaning: "to run/leap/jump" },
        { korean: "차다", romanization: "chada", meaning: "to kick" },
        { korean: "자다", romanization: "jada", meaning: "to sleep" },
        { korean: "산책하다", romanization: "sanchaekhada", meaning: "to take a walk" },
        { korean: "되다", romanization: "doeda", meaning: "to become/possible/permittable" },
        { korean: "피다", romanization: "pida", meaning: "to spread open" },
    ],

    "Verbs 3": [
        { korean: "싸다", romanization: "ssada", meaning: "to be cheap" },
        { korean: "깨닫다", romanization: "kkaedatda", meaning: "to realize (irregular ㄷ)" },
        { korean: "고프다", romanization: "gopeuda", meaning: "to be hungry" },
        { korean: "기쁘다", romanization: "gippeuda", meaning: "to be please" },
        { korean: "바쁘다", romanization: "bappeuda", meaning: "to be busy" },
        { korean: "크다", romanization: "keuda", meaning: "to be big" },
        { korean: "나쁘다", romanization: "nappeuda", meaning: "to be bad" },
        { korean: "다르다", romanization: "dareuda", meaning: "to be different" },
        { korean: "빠르다", romanization: "ppareuda", meaning: "to be fast" },
        { korean: "마르다", romanization: "mareuda", meaning: "to be dry" },
        { korean: "이르다", romanization: "ireuda", meaning: "to be early" },
        { korean: "흐르다", romanization: "heureuda", meaning: "to flow" },
        { korean: "높다", romanization: "nopda", meaning: "to be high" },
        { korean: "춥다", romanization: "chupda", meaning: "to be cold (irregular ㅂ)" },
        { korean: "좁다", romanization: "jopda", meaning: "to be narrow (regular ㅂ)" },
        { korean: "깊다", romanization: "gipda", meaning: "to be deep" },
        { korean: "굳다", romanization: "gutda", meaning: "to be hard/stiff (regular ㄷ)" },
        { korean: "맑다", romanization: "malkda", meaning: "to be clear in weather" },
        { korean: "없다", romanization: "eopda", meaning: "to do not have" },
        { korean: "미끄럽다", romanization: "mikkeureapda", meaning: "to be slippery (irregular ㅂ)" },
        { korean: "아름답다", romanization: "areumdapda", meaning: "to be beautiful (irregular ㅂ)" },
        { korean: "시끄럽다", romanization: "sikkeureapda", meaning: "to be noisy (irregular ㅂ)" },
        { korean: "간지럽다", romanization: "ganjirepda", meaning: "to be itchy (irregular ㅂ)" },
        { korean: "어둡다", romanization: "eodupda", meaning: "to be dark (irregular ㅂ)" },
        { korean: "귀엽다", romanization: "gwiyeopda", meaning: "to be cute (irregular ㅂ)" },
        { korean: "어렵다", romanization: "eoryeopda", meaning: "to be difficult (irregular ㅂ)" },
        { korean: "부지런하다", romanization: "bujireonhada", meaning: "to be diligent" }
    ],

    "Regular Verbs (ㅂ ending)": [
        { korean: "입다", romanization: "ipda", meaning: "to wear" },
        { korean: "잡다", romanization: "japda", meaning: "to catch/hold" },
        { korean: "집다", romanization: "jipda", meaning: "to pick" },
        { korean: "줍다", romanization: "jupda", meaning: "to pick" },
        { korean: "씹다", romanization: "ssipda", meaning: "to chew/bite" },
        { korean: "좁다", romanization: "jopda", meaning: "to narrow" }
    ],

    "Regular Verbs (ㄷ ending)": [
        { korean: "걷다", romanization: "geotda", meaning: "to gather/collect" },
        { korean: "닫다", romanization: "datda", meaning: "to close" },
        { korean: "받다", romanization: "batda", meaning: "to receive" },
        { korean: "믿다", romanization: "mitda", meaning: "to believe" },
        { korean: "굳다", romanization: "gutda", meaning: "to be stiff/hard" },
        { korean: "얻다", romanization: "eotda", meaning: "to get/obtain" },
        { korean: "쏟다", romanization: "ssotda", meaning: "to spill" },
        { korean: "묻다", romanization: "mutda", meaning: "to bury" }
    ],

    "Regular Verbs (ㅅ ending)": [
        { korean: "씻다", romanization: "ssitda", meaning: "to wash" },
        { korean: "웃다", romanization: "utda", meaning: "to laugh/smile" },
        { korean: "빗다", romanization: "bitda", meaning: "to comb" },
        { korean: "벗다", romanization: "beotda", meaning: "to wear off (general)" },
        { korean: "솟다", romanization: "sotda", meaning: "to rise" }
    ],

    "Irregular Verbs (ㅂ ending)": [
        { korean: "덥다", romanization: "deopda", meaning: "to be hot (weather)" },
        { korean: "춥다", romanization: "chupda", meaning: "to be cold (weather)" },
        { korean: "쉽다", romanization: "swipda", meaning: "to be easy" },
        { korean: "어렵다", romanization: "eoryeopda", meaning: "to be difficult" },
        { korean: "맵다", romanization: "maepda", meaning: "to be spicy" },
        { korean: "싱겁다", romanization: "singgeopda", meaning: "to be bland" },
        { korean: "가볍다", romanization: "gabyeopda", meaning: "to be light" },
        { korean: "무겁다", romanization: "mugeopda", meaning: "to be heavy" },
        { korean: "차갑다", romanization: "chagapda", meaning: "to be cold (touch)" },
        { korean: "뜨겁다", romanization: "tteugeopda", meaning: "to be hot (touch)" },
        { korean: "더럽다", romanization: "deorepda", meaning: "to be dirty" },
        { korean: "어지럽다", romanization: "eojireopda", meaning: "to be dizzy" },
        { korean: "시끄럽다", romanization: "sikkeureapda", meaning: "to be noisy" },
        { korean: "미끄럽다", romanization: "mikkeureapda", meaning: "to be slippery" },
        { korean: "외롭다", romanization: "oeropda", meaning: "to be lonely" },
        { korean: "고맙다", romanization: "gomapda", meaning: "to be thankful" },
        { korean: "가깝다", romanization: "gakkapda", meaning: "to be near" },
        { korean: "즐겁다", romanization: "jeulgeopda", meaning: "to be enjoyable" },
        { korean: "무섭다", romanization: "museopda", meaning: "to be scary" },
        { korean: "아름답다", romanization: "areumdapda", meaning: "to be beautiful" },
        { korean: "그립다", romanization: "geuripda", meaning: "to miss (person)" },
        { korean: "굽다", romanization: "gupda", meaning: "to roast/bake" },
        { korean: "돕다", romanization: "dopda", meaning: "to help" },
        { korean: "눕다", romanization: "nupda", meaning: "to lie down" },
        { korean: "부럽다", romanization: "bureopda", meaning: "to be envious" }
    ],

    "Irregular Verbs (ㄷ ending)": [
        { korean: "걷다", romanization: "geotda", meaning: "to walk" },
        { korean: "듣다", romanization: "deutda", meaning: "to listen" },
        { korean: "묻다", romanization: "mutda", meaning: "to ask" },
        { korean: "싣다", romanization: "sitda", meaning: "to load (vehicles)" },
        { korean: "긷다", romanization: "gitda", meaning: "to draw water (well)" },
        { korean: "깨닫다", romanization: "kkaedatda", meaning: "to realize" }
    ],

    "Irregular Verbs (ㅅ ending)": [
        { korean: "낫다", romanization: "natda", meaning: "to recover" },
        { korean: "짓다", romanization: "jitda", meaning: "to build" },
        { korean: "붓다", romanization: "butda", meaning: "to swell/to pour" },
        { korean: "잇다", romanization: "itda", meaning: "to connect or link" },
        { korean: "젓다", romanization: "jeotda", meaning: "to stir/whip" },
        { korean: "긋다", romanization: "geutda", meaning: "to draw (a line)" }
    ],

    "Irregular Verbs (ㄹ ending)": [
        { korean: "살다", romanization: "salda", meaning: "to live" },
        { korean: "팔다", romanization: "palda", meaning: "to sell" },
        { korean: "만들다", romanization: "mandeulda", meaning: "to make" },
        { korean: "열다", romanization: "yeolda", meaning: "to open" },
        { korean: "놀다", romanization: "nolda", meaning: "to play/hang out" },
        { korean: "알다", romanization: "alda", meaning: "to know" },
        { korean: "울다", romanization: "ulda", meaning: "to cry" },
        { korean: "걸다", romanization: "geolda", meaning: "to call/hang" },
        { korean: "졸다", romanization: "jolda", meaning: "to doze off/sleepy" },
        { korean: "쓸다", romanization: "sseulda", meaning: "to sweep" },
        { korean: "풀다", romanization: "pulda", meaning: "to loosen" },
        { korean: "널다", romanization: "neolda", meaning: "to hang (laundry)" },
        { korean: "갈다", romanization: "galda", meaning: "to sharpen (knife)" },
        { korean: "멀다", romanization: "meolda", meaning: "to be far" },
        { korean: "달다", romanization: "dalda", meaning: "to be sweet" },
        { korean: "길다", romanization: "gilda", meaning: "to be long" },
        { korean: "썰다", romanization: "sseolda", meaning: "to chop (thinly/small)" },
        { korean: "힘들다", romanization: "himdeulda", meaning: "to be hard (physically)" },
        { korean: "밀다", romanization: "milda", meaning: "to push" },
        { korean: "끌다", romanization: "kkeulda", meaning: "to pull/drag" },
        { korean: "말다", romanization: "malda", meaning: "to roll" },
        { korean: "들다", romanization: "deulda", meaning: "to enter/to hold" },
        { korean: "물다", romanization: "mulda", meaning: "to bite" },
        { korean: "돌다", romanization: "dolda", meaning: "to turn/rotate" },
        { korean: "벌다", romanization: "beolda", meaning: "to earn" }
    ],

    "Irregular Verbs (ㅡ ending)": [
        { korean: "아프다", romanization: "apeuda", meaning: "to be sick/in pain" },
        { korean: "예쁘다", romanization: "yeppeuda", meaning: "to be pretty" },
        { korean: "바쁘다", romanization: "bappeuda", meaning: "to be busy" },
        { korean: "슬프다", romanization: "seulpeuda", meaning: "to be sad" },
        { korean: "고프다", romanization: "gopeuda", meaning: "to be hungry" },
        { korean: "크다", romanization: "keuda", meaning: "to be big" },
        { korean: "쓰다", romanization: "sseuda", meaning: "to be bitter" },
        { korean: "쓰다", romanization: "sseuda", meaning: "to write" },
        { korean: "쓰다", romanization: "sseuda", meaning: "to use" },
        { korean: "쓰다", romanization: "sseuda", meaning: "to wear (head)" },
        { korean: "나쁘다", romanization: "nappeuda", meaning: "to be bad" },
        { korean: "기쁘다", romanization: "gippeuda", meaning: "to be please" },
        { korean: "잠그다", romanization: "jamgeuda", meaning: "to lock" },
        { korean: "끄다", romanization: "kkeuda", meaning: "to turn off" },
        { korean: "뜨다", romanization: "tteuda", meaning: "to float" },
        { korean: "빠르다", romanization: "ppareuda", meaning: "to be fast" },
        { korean: "바르다", romanization: "bareuda", meaning: "to apply on (lotion)" },
        { korean: "누르다", romanization: "nureuda", meaning: "to press" },
        { korean: "부르다", romanization: "bureuda", meaning: "to call (out)" },
        { korean: "오르다", romanization: "oreuda", meaning: "to ascend" },
        { korean: "자르다", romanization: "jareuda", meaning: "to cut" },
        { korean: "서투르다", romanization: "seotureuda", meaning: "to be clumsy" },
        { korean: "다르다", romanization: "dareuda", meaning: "to be different" },
        { korean: "놀르다", romanization: "nolleuda", meaning: "to be surprise/shock" }
    ],

    "Irregular Verbs (르 ending)": [
        { korean: "이르다", romanization: "ireuda", meaning: "to reach/arrive at" },
        { korean: "마르다", romanization: "mareuda", meaning: "to be dry/skinny" },
        { korean: "들르다", romanization: "deulleuda", meaning: "to stop by" },
        { korean: "모르다", romanization: "moreuda", meaning: "to do not know" },
        { korean: "나르다", romanization: "nareuda", meaning: "to carry" },
        { korean: "고르다", romanization: "goreuda", meaning: "to choose" },
        { korean: "게으르다", romanization: "geeureuda", meaning: "to be lazy" },
        { korean: "서두르다", romanization: "seodureuda", meaning: "to hurry" },
        { korean: "기르다", romanization: "gireuda", meaning: "to raise/grow" },
        { korean: "이르다", romanization: "ireuda", meaning: "to be early" },
        { korean: "흐르다", romanization: "heureuda", meaning: "to flow" },
        { korean: "따르다", romanization: "ttareuda", meaning: "to follow/pour" }
    ],

    "Stative Verb 1": [
        { korean: "시간(이) 있다", romanization: "sigan(i) itda", meaning: "to have time" },
        { korean: "시간(이) 없다", romanization: "sigan(i) eopda", meaning: "not to have time" },
        { korean: "약속(이) 있다", romanization: "yaksok(i) itda", meaning: "to have an appointment" },
        { korean: "약속(이) 없다", romanization: "yaksok(i) eopda", meaning: "not to have an appointment" },
        { korean: "일이 많다", romanization: "iri manta", meaning: "to have a lot of work" },
        { korean: "일이 적다", romanization: "iri jeokda", meaning: "not to have much work" },
        { korean: "바쁘다", romanization: "bappeuda", meaning: "to be busy" },
        { korean: "한가하다", romanization: "hangahada", meaning: "to be free" },
        { korean: "재미있다", romanization: "jaemiitda", meaning: "to be interesting/fun" },
        { korean: "재미없다", romanization: "jaemieopda", meaning: "to be not interesting/boring" },
        { korean: "좋다", romanization: "jota", meaning: "nice" },
        { korean: "괜찮다", romanization: "gwaenchanta", meaning: "fine" }
    ],

    "Stative Verb 2": [
        { korean: "빠르다(이르다)", romanization: "ppareuda(ireuda)", meaning: "early" },
        { korean: "늦다", romanization: "neutda", meaning: "late" },
        { korean: "가깝다", romanization: "gakkapda", meaning: "close" },
        { korean: "멀다", romanization: "meolda", meaning: "far" },
        { korean: "같다", romanization: "gatda", meaning: "same" },
        { korean: "다르다", romanization: "dareuda", meaning: "different" },
        { korean: "간단하다", romanization: "gandanhada", meaning: "simple" },
        { korean: "복잡하다", romanization: "bokjapada", meaning: "complicated" },
        { korean: "편하다", romanization: "pyeonhada", meaning: "comfortable" },
        { korean: "불편하다", romanization: "bulpyeonhada", meaning: "uncomfortable" },
        { korean: "가능하다", romanization: "ganeunghada", meaning: "possible" },
        { korean: "불가능하다", romanization: "bulganeunghada", meaning: "impossible" }
    ],

    "Point of Existence (Marker 에)": [
        { korean: "있다", romanization: "itda", meaning: "to exist" },
        { korean: "없다", romanization: "eopda", meaning: "to not exist" },
        { korean: "살다", romanization: "salda", meaning: "to live" },
        { korean: "많다", romanization: "manta", meaning: "to be many" },
        { korean: "별로 많다", romanization: "byeollo manta", meaning: "to be not many" },
        { korean: "머무르다", romanization: "meomureuda", meaning: "to stay (temporarily, at a place)" },
        { korean: "머물다", romanization: "meomulda", meaning: "to stay (temporarily, at a place)" },
        { korean: "묵다", romanization: "mukda", meaning: "to stay (at a hotel, lodging)" }
    ],

    "Time Verbs (Marker 에)": [
        { korean: "시작하다", romanization: "sijakhada", meaning: "to start" },
        { korean: "끝나다", romanization: "kkeunnada", meaning: "to end" },
        { korean: "출발하다", romanization: "chulbalhada", meaning: "to depart" },
        { korean: "도착하다", romanization: "dochakhada", meaning: "to arrive" },
        { korean: "출근하다", romanization: "chulgeunhada", meaning: "to go to work" },
        { korean: "퇴근하다", romanization: "toegeunhada", meaning: "to leave work" }
    ],

    "Placement/Containment Verbs (Marker 에)": [
        { korean: "놓다", romanization: "nota", meaning: "to put (place)" },
        { korean: "넣다", romanization: "neota", meaning: "to put into" },
        { korean: "담다", romanization: "damda", meaning: "to put into a container" },
        { korean: "두다", romanization: "duda", meaning: "to put (leave intentionally in placed)" },
        { korean: "올리다", romanization: "ollida", meaning: "to put/raised into" },
        { korean: "꽂다", romanization: "kkotda", meaning: "to stick/insert" },
        { korean: "걸다", romanization: "geolda", meaning: "to hang" },
        { korean: "붙이다", romanization: "buchida", meaning: "to stick/attach" },
        { korean: "쌓다", romanization: "ssata", meaning: "to pile" },
        { korean: "넣어두다", romanization: "neoeoduda", meaning: "to keep/store in" }
    ],

    "Movement Verbs (Marker 에)": [
        { korean: "가다", romanization: "gada", meaning: "to go" },
        { korean: "오다", romanization: "oda", meaning: "to come" },
        { korean: "다니다", romanization: "danida", meaning: "to attend/go regularly" },
        { korean: "나다", romanization: "nada", meaning: "to come out" },
        { korean: "들어가다", romanization: "deureogada", meaning: "to enter/to go in" },
        { korean: "들어오다", romanization: "deureooda", meaning: "to come in" },
        { korean: "돌아가다", romanization: "doragada", meaning: "to return/go back" },
        { korean: "돌아오다", romanization: "doraoda", meaning: "to come back" },
        { korean: "출근하다", romanization: "chulgeunhada", meaning: "to go to work" },
        { korean: "퇴근하다", romanization: "toegeunhada", meaning: "to leave work" },
        { korean: "출발하다", romanization: "chulbalhada", meaning: "to depart" },
        { korean: "도착하다", romanization: "dochakhada", meaning: "to arrive" },
        { korean: "내려가다", romanization: "naeryeogada", meaning: "to go down" },
        { korean: "내려오다", romanization: "naeryeooda", meaning: "to come down" },
        { korean: "올라가다", romanization: "ollagada", meaning: "to go up" },
        { korean: "올라오다", romanization: "ollaoda", meaning: "to come up" },
        { korean: "나가다", romanization: "nagada", meaning: "to go out" },
        { korean: "나오다", romanization: "naoda", meaning: "to come out" },
    ],

    "Location Words": [
        { korean: "위", romanization: "wi", meaning: "on / above / up" },
        { korean: "밑/아래", romanization: "mit/arae", meaning: "under / below / down" },
        { korean: "앞", romanization: "ap", meaning: "front" },
        { korean: "뒤", romanization: "dwi", meaning: "behind / back" },
        { korean: "안/속", romanization: "an/sok", meaning: "inside" },
        { korean: "밖", romanization: "bak", meaning: "outside" },
        { korean: "옆", romanization: "yeop", meaning: "beside / next to" },
        { korean: "사이", romanization: "sai", meaning: "in between" },
        { korean: "가운데/중간", romanization: "gaunde/junggan", meaning: "in the middle" },
        { korean: "건너편 (맞은편)", romanization: "geonneopyeon (majeunpyeon)", meaning: "opposite side / across the street" },
        { korean: "우회전", romanization: "uhoejeon", meaning: "right turn" },
        { korean: "좌회전", romanization: "jwahoejeon", meaning: "left turn" },
        { korean: "오른쪽", romanization: "oreunjjok", meaning: "right" },
        { korean: "왼쪽", romanization: "oenjjok", meaning: "left" }
    ],

    "Signs": [
        { korean: "앞으로 가세요", romanization: "apeuro gaseyo", meaning: "Go forward" },
        { korean: "뒤로 가세요", romanization: "dwiro gaseyo", meaning: "Go backward" },
        { korean: "오른쪽으로 가세요", romanization: "oreunjjok-euro gaseyo", meaning: "Go right" },
        { korean: "왼쪽으로 가세요", romanization: "oenjjok-euro gaseyo", meaning: "Go left" },
        { korean: "위로 올라가세요", romanization: "wiro ollagaseyo", meaning: "Go up" },
        { korean: "아래로 내려가세요", romanization: "araero naeryeogaseyo", meaning: "Go down" }
    ],
});
