if (typeof flashcardData === 'undefined') var flashcardData = {};

Object.assign(flashcardData, {
       // NEW NUMBER PRACTICE CATEGORIES
    "Numbers Practice - Prices (Sino-Korean)": [],
    "Numbers Practice - Dates (Sino-Korean)": [],
    "Numbers Practice - Native Korean (1-20)": [],
    "Numbers Practice - Phone Numbers": [],
    "Telling Time (12hr)": [],

    "Counter Units (Native)": [
        { korean: "동", romanization: "dong", meaning: "block of buildings/houses" },
        { korean: "번/회", romanization: "beon/hwe", meaning: "no. of action done" },
        { korean: "정", romanization: "jeong", meaning: "no. of pieces of medicine" },
        { korean: "공기", romanization: "gonggi", meaning: "rice in a bowl" },
        { korean: "그릇", romanization: "geureut", meaning: "dish serve in bowl" },
        { korean: "접시", romanization: "jeopsi", meaning: "no. of dish serve in plate" },
        { korean: "조각", romanization: "jogak", meaning: "slices of food" },
        { korean: "가지", romanization: "gaji", meaning: "categories, kinds, sorts, groups, ways" },
        { korean: "통", romanization: "tong", meaning: "big round fruits / no. of phone calls/ emails/ letters / large round container" },
        { korean: "묶음", romanization: "mukeum", meaning: "bundle/package" },
        { korean: "포기", romanization: "pogi", meaning: "plants from roots" },
        { korean: "줄", romanization: "jul", meaning: "things arranged in lines" },
        { korean: "판", romanization: "pan", meaning: "dish serve in plate" },
        { korean: "바구니", romanization: "baguni", meaning: "basket of items" },
        { korean: "장", romanization: "jang", meaning: "thin/flat objects" },
        { korean: "송이", romanization: "songi", meaning: "bunches/stems" },
        { korean: "척", romanization: "cheok", meaning: "ships" },
        { korean: "개", romanization: "gae", meaning: "general items" },
        { korean: "갑", romanization: "gap", meaning: "handful of box" },
        { korean: "상자", romanization: "sangja", meaning: "no. of large box" },
        { korean: "봉지", romanization: "bongji", meaning: "bags of small things" },
        { korean: "포대", romanization: "podae", meaning: "sacks of items" },
        { korean: "잔", romanization: "jan", meaning: "no. of cups/glasses" },
        { korean: "병", romanization: "byeong", meaning: "no. of bottles" },
        { korean: "권", romanization: "gwon", meaning: "binded things/books" },
        { korean: "잎", romanization: "ip", meaning: "no. of leaves/petals" },
        { korean: "그루", romanization: "geuru", meaning: "no. of trees" },
        { korean: "마리", romanization: "mari", meaning: "no. of animals" },
        { korean: "채", romanization: "chae", meaning: "units of houses" },
        { korean: "살", romanization: "sal", meaning: "Age (years old)" },
        { korean: "분/명/사람", 
        romanization: "bun/myeong/saram", 
        meaning: "collective of people - 분 (honorific/polite for guests, elders), 명 (general/neutral for counting people), 사람 (natural/casual, also means 'person' or nationality)" },
        { korean: "시간", romanization: "sigan", meaning: "duration of time" },
        { korean: "시", romanization: "si", meaning: "no. of hours" },
        { korean: "달", romanization: "dal", meaning: "duration of months" },
        { korean: "벌", romanization: "beol", meaning: "pair of clothes / set of clothes" },
        { korean: "켤레", romanization: "kyeollae", meaning: "pair of things that wear on feet/hands" },
        { korean: "쌍", romanization: "ssang", meaning: "pair of animals, people and some special object" },
        { korean: "대", romanization: "dae", meaning: "machines/appliances/vehicles/musical instruments" },
        { korean: "자루", romanization: "jaru", meaning: "long handled things/tools" }
    ],

    "Counter Units (Sino)": [
        { korean: "번", romanization: "beon", meaning: "number" },
        { korean: "호", romanization: "ho", meaning: "no. of house/rooms" },
        { korean: "세", romanization: "se", meaning: "age" },
        { korean: "년", romanization: "nyeon", meaning: "years and duration" },
        { korean: "월", romanization: "wol", meaning: "months of the year" },
        { korean: "일", romanization: "il", meaning: "dates and days" },
        { korean: "박", romanization: "bak", meaning: "number of nights" },
        { korean: "개월", romanization: "gaewol", meaning: "duration of months" },
        { korean: "주", romanization: "ju", meaning: "number of weeks" },
        { korean: "분", romanization: "bun", meaning: "no. of minutes" },
        { korean: "초", romanization: "cho", meaning: "number of seconds" },
        { korean: "인분", romanization: "inbun", meaning: "portions of food" },
        { korean: "층", romanization: "cheung", meaning: "no. of floors" },
        { korean: "원", romanization: "won", meaning: "korean currency" }
    ]
});